### ISSUE TITLE
notifications param in request

### ISSUE THREAD

**Issue by mhipo1364** [Pushwoosh/pushwoosh-python-lib#2]
Hi

I'm going to send push to some devices which have push_tokens, and I have to fill the notifications.devices with this push_tokens, but command object doesn't have notification, or I couldn't find it, would you like to help about this issue?

**Comment by NastyaL** [comment]
Hey,

In order to make this work you need to use Notification object and CreateMessageForApplicationCommand или CreateMessageForApplicationGroupCommand for sending out to specific app or groups of app.

In turn, Notification uses the following parameters: “platforms", “devices", “filter" and “conditions".

Here is a code sample:

```
from pypushwoosh.client import PushwooshClient
from pypushwoosh.command import CreateMessageForApplicationCommand
from pypushwoosh.notification import Notification

AUTH_TOKEN = 'AUTH_TOKEN'
APPLICATION_CODE = 'APP-CODE'

notification = Notification()
notification.content = 'Hello world!'
notification.devices = [
    'PUSH_TOKEN_0',
    'PUSH_TOKEN_1',
]

command = CreateMessageForApplicationCommand(notification, APPLICATION_CODE)
command.auth = AUTH_TOKEN

client = PushwooshClient()
response = client.invoke(command)
```
If you would like to use CreateTargetedMessageCommand and its devices_filter, you cannot do that. Please refer to the Advanced Tags Guide:

Note that you cannot use any of the following targeting-related parameters in the /createTargetedMessage request: "application", "applications_group", "platforms", "devices", "filter", "conditions"

The syntax will be different, and it is based exclusively on Tags conditions. Please note that in some cases Tags and Conditions are strongly recommended, since push tokens can change over time.
